# Generated by Django 5.0.7 on 2024-07-26 16:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.frameFile)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
